# 데이터 경로
data: '/data/ephemeral/home/data/train/train_ratings.csv'

# 모델 설정
model:
  max_len: 100
  hidden_units: 64
  num_heads: 4
  num_layers: 3
  dropout_rate: 0.3

# 학습 설정
train:
  lr: 0.0015
  batch_size: 128
  num_epochs: 200
  mask_prob: 0.15 # for cloze task
  num_workers: 1
  save_dir: 'checkpoints'
  save_every: 20

# 추론 설정
inference:
  topk: 10
  batch_size: 256
  output_path: outputs/inference.csv
  # checkpoint_path: checkpoint_epoch_180.pt