data:
  interaction_path: "/data/ephemeral/home/data/train/train_ratings.csv"
  title_path: "/data/ephemeral/home/data/train/titles.tsv"
  genre_path: "/data/ephemeral/home/data/train/Ml_item2attributes.json"
  year_path: "/data/ephemeral/home/data/train/years.tsv"
  directors_path: "/data/ephemeral/home/data/train/directors.tsv"
  submission_path: "/data/ephemeral/home/data/train/sample_submission.csv"

train:
  iterations: 5000
  learning_rate: 0.01
  depth: 6
  loss_function: YetiRank
  eval_metric: RecallAt:top=10
  task_type: GPU
  verbose: 100
  random_seed: 42
  n_negative: 10
  model_path: "checkpoints/catboost_ranker.cbm"

inference:
  model_path: "checkpoints/catboost_ranker.cbm"
  top_k: 10
  use_gpu: true
  batch_size: 500
